// <auto-generated />
using System;
using ApiBloodyTree.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiBloodyTree.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230902202533_005")]
    partial class _005
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiBloodyTree.Model.Membro", b =>
                {
                    b.Property<int>("IdMembro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMembro"));

                    b.Property<bool?>("FatorRh")
                        .HasColumnType("bit");

                    b.Property<double?>("GrupoA")
                        .HasColumnType("float");

                    b.Property<double?>("GrupoAB")
                        .HasColumnType("float");

                    b.Property<double?>("GrupoB")
                        .HasColumnType("float");

                    b.Property<double?>("GrupoO")
                        .HasColumnType("float");

                    b.Property<int?>("IdConjuge")
                        .HasColumnType("int");

                    b.Property<int?>("IdIrmao")
                        .HasColumnType("int");

                    b.Property<int?>("IdMae")
                        .HasColumnType("int");

                    b.Property<int?>("IdPai")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PortadorNegativo")
                        .HasColumnType("bit");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMembro");

                    b.ToTable("Membros");
                });
#pragma warning restore 612, 618
        }
    }
}
